[workspace]
resolver = "2"

members = [
    "./irust_prompt",
    "./irust_vim_dylib",
    "./ipython",
    "./fun",
    "./irust_animation",
    "./mixed_cmds",
    "./super_add",
]

[workspace.dependencies]
irust_api = { path = "../crates/irust_api/" }
rscript = "0.17.0"
