[package]
name = "irust_vim_dylib"
version = "0.1.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irust_api.workspace = true
rscript.workspace = true

[lib]
crate-type = ["cdylib"]
