[package]
name = "ipython"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irust_api.workspace = true
rscript.workspace = true
